name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
#    services:
#      registry:
#        image: registry:2
#        ports:
#          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

#        name: Login to Nexus repo
#        uses: sonatype-nexus-community/nexus-repo-github-action@master
#        with:
#          serverUrl: http://183.105.120.175:7003
#          username: admin
#          password: ${{ secrets.NEXUS_PASSWORD }}
#      -
#        name: Replace Docker config before push
#        run: |
#          echo {"insecure-registries" : ["183.105.120.175:2224"]} >> /etc/docker/daemon.json
      -
        name: Login to Nexus
        uses: docker/login-action@v1
        with:
          registry: 183.105.120.175:2224
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}


      -
        name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          #push: true
          tags: |
            183.105.120.175:2224/data-pipeline-atom-serve:latest
          load: true
      -
        name: Push docker image on Nexus repository
        run: |
          docker push 183.105.120.175:2224/data-pipeline-atom-serve:latest
#      -
#        name: Inspect
#        run: |
#          docker buildx imagetools inspect sangkyulee/data-pipeline-atom-serve:latest
      -
        name: Notify failure
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          username: 이상규
          channel: '#alarm'
        if: failure()

