name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Nexus repo
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: 183.105.120.175
          username: admin
          password: ${{ secrets.password }}
          fotmat: docker
          repository: docker-hosted
      -
        name: Build and push to registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 183.105.120.175:/docker-hosted/data-pipeline-atom-serve:latest
      -
        name: Inspect
        run: |
          docker buildx imagetools inspect 183.105.120.175:/docker-hosted/data-pipeline-atom-serve:latest
