name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Nexus repo
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://183.105.120.175:7003
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}

      -
        name: Build and push to registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 183.105.120.175:/docker-hosted/data-pipeline-atom-serve:latest
      -
        name: Inspect
        run: |
          docker buildx imagetools inspect 183.105.120.175:/docker-hosted/data-pipeline-atom-serve:latest
      -
        name: Notify failure
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          username: 이상규
          channel: '#mlops-개발'
        if: failure()

